name: Docker Build And Push To Container Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |-
          docker build -t ${{ github.event.repository.name }}:latest .

      - name: Save Docker Image
        run: |-
          docker save -o ./${{ github.event.repository.name }}:latest.tar ${{ github.event.repository.name }}:latest
          chmod 664 ${{ github.event.repository.name }}:latest.tar

      - name: Send Docker image to Host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          source: ${{ github.event.repository.name }}:latest.tar
          target: /home/elemes/temp

